name: benchmarks

on: 
  pull_request:
    types:
      - opened
      - reopened
  issue_comment:
    types:
      - created

jobs:
  run_benchmarks:
    runs-on: ubuntu-latest
    # run either when pull request is opened or when comment body (only on pr) is /run-bench
    if: (github.event_name == 'pull_request') || ((github.event.issue.pull_request != null) && github.event.comment.body == '/run-bench')
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install hyperfine
        run: cargo install hyperfine
      - name: Install cmake
        run: apt update && apt install cmake -y